 
before_script:
  - apt update -qq
  - ./install-deps.sh
 
stages:
  - build-amd64
  - build-i386

build-amd64:
  stage: build
  image: amd64/debian:unstable
  script:
    - ./autogen.sh
    - ./configure
    - make distclean
    - (cd libltdl; make distclean)
    - dpkg-buildpackage -uc -us -d -b
    - mv ../*.deb build/debian
  
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

build-i386:
  stage: build
  image: i386/debian:unstable
  script:
    - ./autogen.sh
    - ./configure
    - make distclean
    - (cd libltdl; make distclean)
    - dpkg-buildpackage -uc -us -d -b
    - mv ../*i386*.deb build/debian
  
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*
