 
before_script:
  # - apt update -qq
  # - ./install-deps.sh
 
stages:
  - build-amd64
  - build-i386

build-amd64:
  stage: build-amd64
  # image: amd64/debian:unstable
  image: forthy42/gforth-builder-linux-amd64:unstable
  script:
    - ./autogen.sh
    - ./configure
    - make distclean
    - dpkg-buildpackage -uc -us -d -b
    - rm -f debian/*.deb
    - mv ../*.deb debian
  
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*
      - debian/*.deb

build-i386:
  stage: build-i386
  # image: i386/debian:unstable
  image: forthy42/gforth-builder-linux-i386:unstable
  script:
    - ./autogen.sh
    - ./configure --host=i686-pc-linux-gnu --build=i686-pc-linux-gnu
    - make distclean
    - dpkg-buildpackage -uc -us -d -b -ai386
    - mv ../*i386*.deb debian
  
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*
      - debian/*.deb

build-amd64-stable:
  stage: build-amd64
  # image: amd64/debian:stable
  image: forthy42/gforth-builder-linux-amd64:stable
  script:
    - ./autogen.sh
    - ./configure
    - make distclean
    - dpkg-buildpackage -uc -us -d -b
    - mkdir -p debian/stable
    - rm -f debian/stable/*.deb
    - mv ../*.deb debian/stable
  
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*
      - debian/stable/*.deb

build-i386-stable:
  stage: build-i386
  #image: i386/debian:stable
  image: forthy42/gforth-builder-linux-i386:stable
  script:
    - ./autogen.sh
    - ./configure --host=i686-pc-linux-gnu --build=i686-pc-linux-gnu
    - make distclean
    - dpkg-buildpackage -uc -us -d -b -ai386
    - mv ../*i386*.deb debian/stable
  
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*
      - debian/stable/*.deb

build-amd64-oldstable:
  stage: build-amd64
  # image: amd64/debian:oldstable
  image: forthy42/gforth-builder-linux-amd64:oldstable
  script:
    - ./autogen.sh
    - ./configure
    - make distclean
    - dpkg-buildpackage -uc -us -d -b
    - mkdir -p debian/oldstable
    - rm -f debian/oldstable/*.deb
    - mv ../*.deb debian/oldstable
  
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*
      - debian/oldstable/*.deb

build-i386-oldstable:
  stage: build-i386
  # image: i386/debian:oldstable
  image: forthy42/gforth-builder-linux-i386:oldstable
  script:
    - ./autogen.sh
    - ./configure --host=i686-pc-linux-gnu --build=i686-pc-linux-gnu
    - make distclean
    - dpkg-buildpackage -uc -us -d -b -ai386
    - mv ../*i386*.deb debian/oldstable
  
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*
      - debian/oldstable/*.deb
