 
before_script:
  - apt update -qq
  - ./install-deps.sh
 
stages:
  - build-amd64
  - build-i386

build-amd64:
  stage: build-amd64
  image: amd64/debian:unstable
  script:
    - ./autogen.sh
    - ./configure
    - make distclean
    - (cd libltdl; make distclean)
    - dpkg-buildpackage -uc -us -d -b
    - rm debian/*.deb
    - mv ../*.deb debian
  
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*
      - debian/*.deb

build-i386:
  stage: build-i386
  image: i386/debian:unstable
  script:
    - ./autogen.sh
    - ./configure --host=i686-pc-linux-gnu --build=i686-pc-linux-gnu
    - make distclean
    - (cd libltdl; make distclean)
    - dpkg-buildpackage -uc -us -d -b
    - mv ../*i386*.deb debian
  
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*
      - debian/*.deb
